runtime: python39 # L'environnement d'exécution Python

entrypoint: gunicorn -b :$PORT main:app # Point d'entrée pour Gunicorn

# instance_class: F1 # La classe d'instance (optionnel, dépend de vos besoins)

env_variables:
  SECRET_KEY: "your-secret-key"



